import{a as n,S as m,i}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();n.defaults.baseURL="https://pixabay.com/api/";n.defaults.params={key:"52836672-a9b4603c312b0d6cca2d3ae03",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:21};const f=o=>n.get("",{params:{q:o}}).then(r=>r.data.hits),c=document.querySelector("ul.gallery"),p=document.querySelector("span.loader"),g=new m(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),y=o=>{c.insertAdjacentHTML("beforeend",o.map(({webformatURL:r,largeImageURL:s,tags:l,likes:e,views:t,comments:a,downloads:d})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${s}">
                        <img class="gallery-image" src="${r}" alt="${l}" />
                    </a>
                    <div class="gallery-item-info">
                        <p class="gallery-text"><span class="title">Likes</span>${e}</p>
                        <p class="gallery-text"><span class="title">Views</span>${t}</p>
                        <p class="gallery-text"><span class="title">Comments</span>${a}</p>
                        <p class="gallery-text"><span class="title">Downloads</span>${d}</p>
                    </div>
                </li>
                `).join("")),g.refresh()},h=()=>{c.innerHTML=""},b=()=>{p.classList.add("is-visible")},L=()=>{p.classList.remove("is-visible")},u=document.querySelector(".form"),B=document.querySelector('input[name="search-text"]');u.addEventListener("submit",v);function v(o){o.preventDefault();const r=B.value.trim();if(!r){i.error({message:"Enter a valid keyword!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}h(),b(),f(r).then(s=>{if(s.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}y(s)}).catch(s=>{console.log(s),i.error({message:"Something went wrong. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}).finally(()=>{L(),u.reset()})}
//# sourceMappingURL=index.js.map
