import{a as g,i as a,S as v}from"./assets/vendor-xwsNXkQR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();g.defaults.baseURL="https://pixabay.com/api/";g.defaults.params={key:"52836672-a9b4603c312b0d6cca2d3ae03",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15};const y=async(r,s)=>{try{const e=await g.get("",{params:{q:r,page:s}});if(!e.data||!e.data.hits)throw a.error({message:"Something went wrong with Pixabay API.",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}),new Error("Invalid response");return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.log("Error from Pixabay API: ",e.message),a.error({message:"Failed to fetch emages from Pixabay. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}),e}},h=document.querySelector("ul.gallery"),b=document.querySelector("span.loader"),B=document.querySelector(".load-more-btn"),P=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),C=r=>{h.insertAdjacentHTML("beforeend",r.map(({webformatURL:s,largeImageURL:e,tags:n,likes:t,views:o,comments:l,downloads:x})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${e}">
                        <img class="gallery-image" src="${s}" alt="${n}" />
                    </a>
                    <div class="gallery-item-info">
                        <p class="gallery-text"><span class="title">Likes</span>${t}</p>
                        <p class="gallery-text"><span class="title">Views</span>${o}</p>
                        <p class="gallery-text"><span class="title">Comments</span>${l}</p>
                        <p class="gallery-text"><span class="title">Downloads</span>${x}</p>
                    </div>
                </li>
                `).join("")),P.refresh()},S=()=>{h.innerHTML=""},w=()=>{b.classList.add("is-visible")},L=()=>{b.classList.remove("is-visible")},E=()=>{B.classList.add("is-visible")},m=()=>{B.classList.remove("is-visible")},p=document.querySelector(".form"),q=document.querySelector('input[name="search-text"]'),f=p.querySelector('button[type="submit"]'),c=document.querySelector(".load-more-btn");let d="",i=1,u=0;m();p.addEventListener("submit",F);c.addEventListener("click",M);async function F(r){r.preventDefault();const s=q.value.trim();if(!s){a.error({message:"Enter a valid keyword!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}d=s,i=1,S(),m(),w(),f.disabled=!0;try{const e=await y(d,i);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}u=e.totalHits,C(e.hits),i*15<u&&E()}catch(e){console.log(e),a.error({message:"Something went wrong. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}finally{L(),f.disabled=!1,p.reset()}}async function M(){i+=1,w(),c.disabled=!0;try{const r=await y(d,i);C(r.hits),i*15>=u&&(m(),a.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}))}catch(r){console.log(r),a.error({message:"Something went wrong with loading. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}finally{L(),c.disabled=!1}}
//# sourceMappingURL=index.js.map
