import{a as g,i as a,S as x}from"./assets/vendor-xwsNXkQR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=e(o);fetch(o.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";g.defaults.params={key:"52836672-a9b4603c312b0d6cca2d3ae03",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15};const h=async(t,s)=>{try{const e=await g.get("",{params:{q:t,page:s}});if(!e.data||!e.data.hits)throw a.error({message:"Something went wrong with Pixabay API.",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}),new Error("Invalid response");return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.log("Error from Pixabay API: ",e.message),a.error({message:"Failed to fetch images from Pixabay. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}),e}},y=document.querySelector("ul.gallery"),b=document.querySelector("span.loader"),B=document.querySelector(".load-more-btn"),S=new x(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),C=t=>{y.insertAdjacentHTML("beforeend",t.map(({webformatURL:s,largeImageURL:e,tags:n,likes:o,views:r,comments:l,downloads:v})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${e}">
                        <img class="gallery-image" src="${s}" alt="${n}" />
                    </a>
                    <div class="gallery-item-info">
                        <p class="gallery-text"><span class="title">Likes</span>${o}</p>
                        <p class="gallery-text"><span class="title">Views</span>${r}</p>
                        <p class="gallery-text"><span class="title">Comments</span>${l}</p>
                        <p class="gallery-text"><span class="title">Downloads</span>${v}</p>
                    </div>
                </li>
                `).join("")),S.refresh()},P=()=>{y.innerHTML=""},w=()=>{b.classList.add("is-visible")},L=()=>{b.classList.remove("is-visible")},E=()=>{B.classList.add("is-visible")},m=()=>{B.classList.remove("is-visible")},f=document.querySelector(".form"),q=document.querySelector('input[name="search-text"]'),p=f.querySelector('button[type="submit"]'),c=document.querySelector(".load-more-btn");let d="",i=1,u=0;m();f.addEventListener("submit",F);c.addEventListener("click",R);async function F(t){t.preventDefault();const s=q.value.trim();if(!s){a.error({message:"Enter a valid keyword!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}d=s,i=1,P(),m(),w(),p.disabled=!0;try{const e=await h(d,i);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432});return}u=e.totalHits,C(e.hits),i*15<u?E():a.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}catch(e){console.log(e),a.error({message:"Something went wrong. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}finally{L(),p.disabled=!1,f.reset()}}async function R(){i+=1,w(),c.disabled=!0;try{const t=await h(d,i);C(t.hits),i*15>=u&&(m(),a.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432}))}catch(t){console.log(t),a.error({message:"Something went wrong with loading. Please try again later!",position:"topRight",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",messageColor:"#fff",close:!0,maxWidth:432})}finally{L(),c.disabled=!1,W()}}function W(){const t=document.querySelector(".gallery-item");t&&window.scrollBy({top:t.getBoundingClientRect().height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
